/**
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdditionalAdvancedScanInformation', 'model/CloudStorageAdvancedVirusScanResult', 'model/CloudStorageVirusFound', 'model/CloudStorageVirusScanResult', 'model/VirusFound', 'model/VirusScanAdvancedResult', 'model/VirusScanResult', 'model/WebsiteScanRequest', 'model/WebsiteScanResult', 'api/ScanApi', 'api/ScanCloudStorageApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AdditionalAdvancedScanInformation'), require('./model/CloudStorageAdvancedVirusScanResult'), require('./model/CloudStorageVirusFound'), require('./model/CloudStorageVirusScanResult'), require('./model/VirusFound'), require('./model/VirusScanAdvancedResult'), require('./model/VirusScanResult'), require('./model/WebsiteScanRequest'), require('./model/WebsiteScanResult'), require('./api/ScanApi'), require('./api/ScanCloudStorageApi'));
  }
}(function(ApiClient, AdditionalAdvancedScanInformation, CloudStorageAdvancedVirusScanResult, CloudStorageVirusFound, CloudStorageVirusScanResult, VirusFound, VirusScanAdvancedResult, VirusScanResult, WebsiteScanRequest, WebsiteScanResult, ScanApi, ScanCloudStorageApi) {
  'use strict';

  /**
   * The_Cloudmersive_Virus_Scan_API_lets_you_scan_files_and_content_for_viruses_and_identify_security_issues_with_content_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CloudmersiveVirusApiClient = require('index'); // See note below*.
   * var xxxSvc = new CloudmersiveVirusApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CloudmersiveVirusApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CloudmersiveVirusApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CloudmersiveVirusApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.3.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AdditionalAdvancedScanInformation model constructor.
     * @property {module:model/AdditionalAdvancedScanInformation}
     */
    AdditionalAdvancedScanInformation: AdditionalAdvancedScanInformation,
    /**
     * The CloudStorageAdvancedVirusScanResult model constructor.
     * @property {module:model/CloudStorageAdvancedVirusScanResult}
     */
    CloudStorageAdvancedVirusScanResult: CloudStorageAdvancedVirusScanResult,
    /**
     * The CloudStorageVirusFound model constructor.
     * @property {module:model/CloudStorageVirusFound}
     */
    CloudStorageVirusFound: CloudStorageVirusFound,
    /**
     * The CloudStorageVirusScanResult model constructor.
     * @property {module:model/CloudStorageVirusScanResult}
     */
    CloudStorageVirusScanResult: CloudStorageVirusScanResult,
    /**
     * The VirusFound model constructor.
     * @property {module:model/VirusFound}
     */
    VirusFound: VirusFound,
    /**
     * The VirusScanAdvancedResult model constructor.
     * @property {module:model/VirusScanAdvancedResult}
     */
    VirusScanAdvancedResult: VirusScanAdvancedResult,
    /**
     * The VirusScanResult model constructor.
     * @property {module:model/VirusScanResult}
     */
    VirusScanResult: VirusScanResult,
    /**
     * The WebsiteScanRequest model constructor.
     * @property {module:model/WebsiteScanRequest}
     */
    WebsiteScanRequest: WebsiteScanRequest,
    /**
     * The WebsiteScanResult model constructor.
     * @property {module:model/WebsiteScanResult}
     */
    WebsiteScanResult: WebsiteScanResult,
    /**
     * The ScanApi service constructor.
     * @property {module:api/ScanApi}
     */
    ScanApi: ScanApi,
    /**
     * The ScanCloudStorageApi service constructor.
     * @property {module:api/ScanCloudStorageApi}
     */
    ScanCloudStorageApi: ScanCloudStorageApi
  };

  return exports;
}));
