/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AdditionalAdvancedScanInformation', function() {
      beforeEach(function() {
        instance = new CloudmersiveVirusApiClient.AdditionalAdvancedScanInformation();
      });

      it('should create an instance of AdditionalAdvancedScanInformation', function() {
        // TODO: update the code to test AdditionalAdvancedScanInformation
        expect(instance).to.be.a(CloudmersiveVirusApiClient.AdditionalAdvancedScanInformation);
      });

      it('should have the property containsJSON (base name: "ContainsJSON")', function() {
        // TODO: update the code to test the property containsJSON
        expect(instance).to.have.property('containsJSON');
        // expect(instance.containsJSON).to.be(expectedValueLiteral);
      });

      it('should have the property containsXML (base name: "ContainsXML")', function() {
        // TODO: update the code to test the property containsXML
        expect(instance).to.have.property('containsXML');
        // expect(instance.containsXML).to.be(expectedValueLiteral);
      });

      it('should have the property containsImage (base name: "ContainsImage")', function() {
        // TODO: update the code to test the property containsImage
        expect(instance).to.have.property('containsImage');
        // expect(instance.containsImage).to.be(expectedValueLiteral);
      });

      it('should have the property hashSHA1 (base name: "Hash_SHA1")', function() {
        // TODO: update the code to test the property hashSHA1
        expect(instance).to.have.property('hashSHA1');
        // expect(instance.hashSHA1).to.be(expectedValueLiteral);
      });

      it('should have the property relevantSubfileName (base name: "RelevantSubfileName")', function() {
        // TODO: update the code to test the property relevantSubfileName
        expect(instance).to.have.property('relevantSubfileName');
        // expect(instance.relevantSubfileName).to.be(expectedValueLiteral);
      });

      it('should have the property relevantSubfileHashSHA1 (base name: "RelevantSubfileHash_SHA1")', function() {
        // TODO: update the code to test the property relevantSubfileHashSHA1
        expect(instance).to.have.property('relevantSubfileHashSHA1');
        // expect(instance.relevantSubfileHashSHA1).to.be(expectedValueLiteral);
      });

      it('should have the property isAuthenticodeSigned (base name: "IsAuthenticodeSigned")', function() {
        // TODO: update the code to test the property isAuthenticodeSigned
        expect(instance).to.have.property('isAuthenticodeSigned');
        // expect(instance.isAuthenticodeSigned).to.be(expectedValueLiteral);
      });

    });
  });

}));
