/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ScanCloudStorageJobStatusResult', function() {
      beforeEach(function() {
        instance = new CloudmersiveVirusApiClient.ScanCloudStorageJobStatusResult();
      });

      it('should create an instance of ScanCloudStorageJobStatusResult', function() {
        // TODO: update the code to test ScanCloudStorageJobStatusResult
        expect(instance).to.be.a(CloudmersiveVirusApiClient.ScanCloudStorageJobStatusResult);
      });

      it('should have the property successful (base name: "Successful")', function() {
        // TODO: update the code to test the property successful
        expect(instance).to.have.property('successful');
        // expect(instance.successful).to.be(expectedValueLiteral);
      });

      it('should have the property asyncJobStatus (base name: "AsyncJobStatus")', function() {
        // TODO: update the code to test the property asyncJobStatus
        expect(instance).to.have.property('asyncJobStatus');
        // expect(instance.asyncJobStatus).to.be(expectedValueLiteral);
      });

      it('should have the property asyncJobID (base name: "AsyncJobID")', function() {
        // TODO: update the code to test the property asyncJobID
        expect(instance).to.have.property('asyncJobID');
        // expect(instance.asyncJobID).to.be(expectedValueLiteral);
      });

      it('should have the property result (base name: "Result")', function() {
        // TODO: update the code to test the property result
        expect(instance).to.have.property('result');
        // expect(instance.result).to.be(expectedValueLiteral);
      });

      it('should have the property jobDuration (base name: "JobDuration")', function() {
        // TODO: update the code to test the property jobDuration
        expect(instance).to.have.property('jobDuration');
        // expect(instance.jobDuration).to.be(expectedValueLiteral);
      });

      it('should have the property errorMessage (base name: "ErrorMessage")', function() {
        // TODO: update the code to test the property errorMessage
        expect(instance).to.have.property('errorMessage');
        // expect(instance.errorMessage).to.be(expectedValueLiteral);
      });

    });
  });

}));
