/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ScanCloudStorageJobStatusResult', function() {
      beforeEach(function() {
        instance = new CloudmersiveVirusApiClient.ScanCloudStorageJobStatusResult();
      });

      it('should create an instance of ScanCloudStorageJobStatusResult', function() {
        // TODO: update the code to test ScanCloudStorageJobStatusResult
        expect(instance).to.be.a(CloudmersiveVirusApiClient.ScanCloudStorageJobStatusResult);
      });

      it('should have the property Successful (base name: "Successful")', function() {
        // TODO: update the code to test the property Successful
        expect(instance).to.have.property('Successful');
        // expect(instance.Successful).to.be(expectedValueLiteral);
      });

      it('should have the property AsyncJobStatus (base name: "AsyncJobStatus")', function() {
        // TODO: update the code to test the property AsyncJobStatus
        expect(instance).to.have.property('AsyncJobStatus');
        // expect(instance.AsyncJobStatus).to.be(expectedValueLiteral);
      });

      it('should have the property AsyncJobID (base name: "AsyncJobID")', function() {
        // TODO: update the code to test the property AsyncJobID
        expect(instance).to.have.property('AsyncJobID');
        // expect(instance.AsyncJobID).to.be(expectedValueLiteral);
      });

      it('should have the property Result (base name: "Result")', function() {
        // TODO: update the code to test the property Result
        expect(instance).to.have.property('Result');
        // expect(instance.Result).to.be(expectedValueLiteral);
      });

      it('should have the property JobDuration (base name: "JobDuration")', function() {
        // TODO: update the code to test the property JobDuration
        expect(instance).to.have.property('JobDuration');
        // expect(instance.JobDuration).to.be(expectedValueLiteral);
      });

      it('should have the property ErrorMessage (base name: "ErrorMessage")', function() {
        // TODO: update the code to test the property ErrorMessage
        expect(instance).to.have.property('ErrorMessage');
        // expect(instance.ErrorMessage).to.be(expectedValueLiteral);
      });

    });
  });

}));
