/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ScanCloudStorageBatchJobCreateResult', function() {
      beforeEach(function() {
        instance = new CloudmersiveVirusApiClient.ScanCloudStorageBatchJobCreateResult();
      });

      it('should create an instance of ScanCloudStorageBatchJobCreateResult', function() {
        // TODO: update the code to test ScanCloudStorageBatchJobCreateResult
        expect(instance).to.be.a(CloudmersiveVirusApiClient.ScanCloudStorageBatchJobCreateResult);
      });

      it('should have the property successful (base name: "Successful")', function() {
        // TODO: update the code to test the property successful
        expect(instance).to.have.property('successful');
        // expect(instance.successful).to.be(expectedValueLiteral);
      });

      it('should have the property asyncJobID (base name: "AsyncJobID")', function() {
        // TODO: update the code to test the property asyncJobID
        expect(instance).to.have.property('asyncJobID');
        // expect(instance.asyncJobID).to.be(expectedValueLiteral);
      });

    });
  });

}));
