/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VirusFound', function() {
      beforeEach(function() {
        instance = new CloudmersiveVirusApiClient.VirusFound();
      });

      it('should create an instance of VirusFound', function() {
        // TODO: update the code to test VirusFound
        expect(instance).to.be.a(CloudmersiveVirusApiClient.VirusFound);
      });

      it('should have the property fileName (base name: "FileName")', function() {
        // TODO: update the code to test the property fileName
        expect(instance).to.have.property('fileName');
        // expect(instance.fileName).to.be(expectedValueLiteral);
      });

      it('should have the property virusName (base name: "VirusName")', function() {
        // TODO: update the code to test the property virusName
        expect(instance).to.have.property('virusName');
        // expect(instance.virusName).to.be(expectedValueLiteral);
      });

    });
  });

}));
