/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VirusScanResult', function() {
      beforeEach(function() {
        instance = new CloudmersiveVirusApiClient.VirusScanResult();
      });

      it('should create an instance of VirusScanResult', function() {
        // TODO: update the code to test VirusScanResult
        expect(instance).to.be.a(CloudmersiveVirusApiClient.VirusScanResult);
      });

      it('should have the property cleanResult (base name: "CleanResult")', function() {
        // TODO: update the code to test the property cleanResult
        expect(instance).to.have.property('cleanResult');
        // expect(instance.cleanResult).to.be(expectedValueLiteral);
      });

      it('should have the property foundViruses (base name: "FoundViruses")', function() {
        // TODO: update the code to test the property foundViruses
        expect(instance).to.have.property('foundViruses');
        // expect(instance.foundViruses).to.be(expectedValueLiteral);
      });

    });
  });

}));
