/**
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveVirusApiClient.ScanCloudStorageApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScanCloudStorageApi', function() {
    describe('scanCloudStorageScanAwsS3File', function() {
      it('should call scanCloudStorageScanAwsS3File successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanAwsS3File
        //instance.scanCloudStorageScanAwsS3File(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanCloudStorageScanAwsS3FileAdvanced', function() {
      it('should call scanCloudStorageScanAwsS3FileAdvanced successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanAwsS3FileAdvanced
        //instance.scanCloudStorageScanAwsS3FileAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanCloudStorageScanAzureBlob', function() {
      it('should call scanCloudStorageScanAzureBlob successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanAzureBlob
        //instance.scanCloudStorageScanAzureBlob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanCloudStorageScanAzureBlobAdvanced', function() {
      it('should call scanCloudStorageScanAzureBlobAdvanced successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanAzureBlobAdvanced
        //instance.scanCloudStorageScanAzureBlobAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanCloudStorageScanGcpStorageFile', function() {
      it('should call scanCloudStorageScanGcpStorageFile successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanGcpStorageFile
        //instance.scanCloudStorageScanGcpStorageFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanCloudStorageScanGcpStorageFileAdvanced', function() {
      it('should call scanCloudStorageScanGcpStorageFileAdvanced successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanGcpStorageFileAdvanced
        //instance.scanCloudStorageScanGcpStorageFileAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanCloudStorageScanSharePointOnlineFile', function() {
      it('should call scanCloudStorageScanSharePointOnlineFile successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanSharePointOnlineFile
        //instance.scanCloudStorageScanSharePointOnlineFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanCloudStorageScanSharePointOnlineFileAdvanced', function() {
      it('should call scanCloudStorageScanSharePointOnlineFileAdvanced successfully', function(done) {
        //uncomment below and update the code to test scanCloudStorageScanSharePointOnlineFileAdvanced
        //instance.scanCloudStorageScanSharePointOnlineFileAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
