/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVirusApiClient);
  }
}(this, function(expect, CloudmersiveVirusApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveVirusApiClient.ScanCloudStorageApi();
  });

  describe('(package)', function() {
    describe('ScanCloudStorageApi', function() {
      describe('scanCloudStorageGetAsyncJobStatus', function() {
        it('should call scanCloudStorageGetAsyncJobStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageGetAsyncJobStatus call and complete the assertions
          /*
          var AsyncJobID = "AsyncJobID_example";

          instance.scanCloudStorageGetAsyncJobStatus(AsyncJobID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.ScanCloudStorageJobStatusResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.AsyncJobStatus).to.be.a('string');
            expect(data.AsyncJobStatus).to.be("");
            expect(data.AsyncJobID).to.be.a('string');
            expect(data.AsyncJobID).to.be("");
            expect(data.Result).to.be.a(CloudmersiveVirusApiClient.CloudStorageAdvancedVirusScanResult);
                  expect(data.Result.Successful).to.be.a('boolean');
              expect(data.Result.Successful).to.be(false);
              expect(data.Result.CleanResult).to.be.a('boolean');
              expect(data.Result.CleanResult).to.be(false);
              expect(data.Result.ContainsExecutable).to.be.a('boolean');
              expect(data.Result.ContainsExecutable).to.be(false);
              expect(data.Result.ContainsInvalidFile).to.be.a('boolean');
              expect(data.Result.ContainsInvalidFile).to.be(false);
              expect(data.Result.ContainsScript).to.be.a('boolean');
              expect(data.Result.ContainsScript).to.be(false);
              expect(data.Result.ContainsPasswordProtectedFile).to.be.a('boolean');
              expect(data.Result.ContainsPasswordProtectedFile).to.be(false);
              expect(data.Result.ContainsRestrictedFileFormat).to.be.a('boolean');
              expect(data.Result.ContainsRestrictedFileFormat).to.be(false);
              expect(data.Result.ContainsMacros).to.be.a('boolean');
              expect(data.Result.ContainsMacros).to.be(false);
              expect(data.Result.ContainsXmlExternalEntities).to.be.a('boolean');
              expect(data.Result.ContainsXmlExternalEntities).to.be(false);
              expect(data.Result.ContainsInsecureDeserialization).to.be.a('boolean');
              expect(data.Result.ContainsInsecureDeserialization).to.be(false);
              expect(data.Result.ContainsHtml).to.be.a('boolean');
              expect(data.Result.ContainsHtml).to.be(false);
              expect(data.Result.ContainsUnsafeArchive).to.be.a('boolean');
              expect(data.Result.ContainsUnsafeArchive).to.be(false);
              expect(data.Result.ContainsOleEmbeddedObject).to.be.a('boolean');
              expect(data.Result.ContainsOleEmbeddedObject).to.be(false);
              expect(data.Result.VerifiedFileFormat).to.be.a('string');
              expect(data.Result.VerifiedFileFormat).to.be("");
              {
                let dataCtr = data.Result.FoundViruses;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                  expect(data.FileName).to.be.a('string');
                  expect(data.FileName).to.be("");
                  expect(data.VirusName).to.be.a('string');
                  expect(data.VirusName).to.be("");
  
                        }
              }
              expect(data.Result.ErrorDetailedDescription).to.be.a('string');
              expect(data.Result.ErrorDetailedDescription).to.be("");
              expect(data.Result.FileSize).to.be.a('number');
              expect(data.Result.FileSize).to.be("0");
              expect(data.Result.ContentInformation).to.be.a(CloudmersiveVirusApiClient.AdditionalAdvancedScanInformation);
                    expect(data.Result.ContentInformation.ContainsJSON).to.be.a('boolean');
                expect(data.Result.ContentInformation.ContainsJSON).to.be(false);
                expect(data.Result.ContentInformation.ContainsXML).to.be.a('boolean');
                expect(data.Result.ContentInformation.ContainsXML).to.be(false);
                expect(data.Result.ContentInformation.ContainsImage).to.be.a('boolean');
                expect(data.Result.ContentInformation.ContainsImage).to.be(false);
                expect(data.Result.ContentInformation.Hash_SHA1).to.be.a('string');
                expect(data.Result.ContentInformation.Hash_SHA1).to.be("");
                expect(data.Result.ContentInformation.RelevantSubfileName).to.be.a('string');
                expect(data.Result.ContentInformation.RelevantSubfileName).to.be("");
                expect(data.Result.ContentInformation.RelevantSubfileHash_SHA1).to.be.a('string');
                expect(data.Result.ContentInformation.RelevantSubfileHash_SHA1).to.be("");
                expect(data.Result.ContentInformation.IsAuthenticodeSigned).to.be.a('boolean');
                expect(data.Result.ContentInformation.IsAuthenticodeSigned).to.be(false);
            expect(data.JobDuration).to.be.a('string');
            expect(data.JobDuration).to.be("");
            expect(data.ErrorMessage).to.be.a('string');
            expect(data.ErrorMessage).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanAwsS3File', function() {
        it('should call scanCloudStorageScanAwsS3File successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanAwsS3File call and complete the assertions
          /*
          var accessKey = "accessKey_example";
          var secretKey = "secretKey_example";
          var bucketRegion = "bucketRegion_example";
          var bucketName = "bucketName_example";
          var keyName = "keyName_example";
          var opts = {};
          opts.roleArn = "roleArn_example";

          instance.scanCloudStorageScanAwsS3File(accessKey, secretKey, bucketRegion, bucketName, keyName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContainsContentModerationRejection).to.be.a('boolean');
            expect(data.ContainsContentModerationRejection).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanAwsS3FileAdvanced', function() {
        it('should call scanCloudStorageScanAwsS3FileAdvanced successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanAwsS3FileAdvanced call and complete the assertions
          /*
          var accessKey = "accessKey_example";
          var secretKey = "secretKey_example";
          var bucketRegion = "bucketRegion_example";
          var bucketName = "bucketName_example";
          var keyName = "keyName_example";
          var opts = {};
          opts.roleArn = "roleArn_example";
          opts.allowExecutables = true;
          opts.allowInvalidFiles = true;
          opts.allowScripts = true;
          opts.allowPasswordProtectedFiles = true;
          opts.allowMacros = true;
          opts.allowXmlExternalEntities = true;
          opts.allowInsecureDeserialization = true;
          opts.allowHtml = true;
          opts.allowUnsafeArchives = true;
          opts.allowOleEmbeddedObject = true;
          opts.allowUnwantedAction = true;
          opts.options = "options_example";
          opts.restrictFileTypes = "restrictFileTypes_example";

          instance.scanCloudStorageScanAwsS3FileAdvanced(accessKey, secretKey, bucketRegion, bucketName, keyName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageAdvancedVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContentInformation).to.be.a(CloudmersiveVirusApiClient.AdditionalAdvancedScanInformation);
                  expect(data.ContentInformation.ContainsJSON).to.be.a('boolean');
              expect(data.ContentInformation.ContainsJSON).to.be(false);
              expect(data.ContentInformation.ContainsXML).to.be.a('boolean');
              expect(data.ContentInformation.ContainsXML).to.be(false);
              expect(data.ContentInformation.ContainsImage).to.be.a('boolean');
              expect(data.ContentInformation.ContainsImage).to.be(false);
              expect(data.ContentInformation.Hash_SHA1).to.be.a('string');
              expect(data.ContentInformation.Hash_SHA1).to.be("");
              expect(data.ContentInformation.RelevantSubfileName).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileName).to.be("");
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be("");
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be.a('boolean');
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanAzureBlob', function() {
        it('should call scanCloudStorageScanAzureBlob successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanAzureBlob call and complete the assertions
          /*
          var connectionString = "connectionString_example";
          var containerName = "containerName_example";
          var blobPath = "blobPath_example";

          instance.scanCloudStorageScanAzureBlob(connectionString, containerName, blobPath, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContainsContentModerationRejection).to.be.a('boolean');
            expect(data.ContainsContentModerationRejection).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanAzureBlobAdvanced', function() {
        it('should call scanCloudStorageScanAzureBlobAdvanced successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanAzureBlobAdvanced call and complete the assertions
          /*
          var connectionString = "connectionString_example";
          var containerName = "containerName_example";
          var blobPath = "blobPath_example";
          var opts = {};
          opts.allowExecutables = true;
          opts.allowInvalidFiles = true;
          opts.allowScripts = true;
          opts.allowPasswordProtectedFiles = true;
          opts.allowMacros = true;
          opts.allowXmlExternalEntities = true;
          opts.allowInsecureDeserialization = true;
          opts.allowHtml = true;
          opts.allowUnsafeArchives = true;
          opts.allowOleEmbeddedObject = true;
          opts.allowUnwantedAction = true;
          opts.options = "options_example";
          opts.restrictFileTypes = "restrictFileTypes_example";

          instance.scanCloudStorageScanAzureBlobAdvanced(connectionString, containerName, blobPath, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageAdvancedVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContentInformation).to.be.a(CloudmersiveVirusApiClient.AdditionalAdvancedScanInformation);
                  expect(data.ContentInformation.ContainsJSON).to.be.a('boolean');
              expect(data.ContentInformation.ContainsJSON).to.be(false);
              expect(data.ContentInformation.ContainsXML).to.be.a('boolean');
              expect(data.ContentInformation.ContainsXML).to.be(false);
              expect(data.ContentInformation.ContainsImage).to.be.a('boolean');
              expect(data.ContentInformation.ContainsImage).to.be(false);
              expect(data.ContentInformation.Hash_SHA1).to.be.a('string');
              expect(data.ContentInformation.Hash_SHA1).to.be("");
              expect(data.ContentInformation.RelevantSubfileName).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileName).to.be("");
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be("");
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be.a('boolean');
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanAzureBlobAdvancedBatchJob', function() {
        it('should call scanCloudStorageScanAzureBlobAdvancedBatchJob successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanAzureBlobAdvancedBatchJob call and complete the assertions
          /*
          var connectionString = "connectionString_example";
          var containerName = "containerName_example";
          var blobPath = "blobPath_example";
          var opts = {};
          opts.allowExecutables = true;
          opts.allowInvalidFiles = true;
          opts.allowScripts = true;
          opts.allowPasswordProtectedFiles = true;
          opts.allowMacros = true;
          opts.allowXmlExternalEntities = true;
          opts.allowInsecureDeserialization = true;
          opts.allowHtml = true;
          opts.allowUnsafeArchives = true;
          opts.allowOleEmbeddedObject = true;
          opts.allowUnwantedAction = true;
          opts.options = "options_example";
          opts.restrictFileTypes = "restrictFileTypes_example";

          instance.scanCloudStorageScanAzureBlobAdvancedBatchJob(connectionString, containerName, blobPath, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.ScanCloudStorageBatchJobCreateResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.AsyncJobID).to.be.a('string');
            expect(data.AsyncJobID).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanGcpStorageFile', function() {
        it('should call scanCloudStorageScanGcpStorageFile successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanGcpStorageFile call and complete the assertions
          /*
          var bucketName = "bucketName_example";
          var objectName = "objectName_example";
          var jsonCredentialFile = "/path/to/file.txt";

          instance.scanCloudStorageScanGcpStorageFile(bucketName, objectName, jsonCredentialFile, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContainsContentModerationRejection).to.be.a('boolean');
            expect(data.ContainsContentModerationRejection).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanGcpStorageFileAdvanced', function() {
        it('should call scanCloudStorageScanGcpStorageFileAdvanced successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanGcpStorageFileAdvanced call and complete the assertions
          /*
          var bucketName = "bucketName_example";
          var objectName = "objectName_example";
          var jsonCredentialFile = "/path/to/file.txt";
          var opts = {};
          opts.allowExecutables = true;
          opts.allowInvalidFiles = true;
          opts.allowScripts = true;
          opts.allowPasswordProtectedFiles = true;
          opts.allowMacros = true;
          opts.allowXmlExternalEntities = true;
          opts.allowInsecureDeserialization = true;
          opts.allowHtml = true;
          opts.allowUnsafeArchives = true;
          opts.allowOleEmbeddedObject = true;
          opts.allowUnwantedAction = true;
          opts.options = "options_example";
          opts.restrictFileTypes = "restrictFileTypes_example";

          instance.scanCloudStorageScanGcpStorageFileAdvanced(bucketName, objectName, jsonCredentialFile, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageAdvancedVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContentInformation).to.be.a(CloudmersiveVirusApiClient.AdditionalAdvancedScanInformation);
                  expect(data.ContentInformation.ContainsJSON).to.be.a('boolean');
              expect(data.ContentInformation.ContainsJSON).to.be(false);
              expect(data.ContentInformation.ContainsXML).to.be.a('boolean');
              expect(data.ContentInformation.ContainsXML).to.be(false);
              expect(data.ContentInformation.ContainsImage).to.be.a('boolean');
              expect(data.ContentInformation.ContainsImage).to.be(false);
              expect(data.ContentInformation.Hash_SHA1).to.be.a('string');
              expect(data.ContentInformation.Hash_SHA1).to.be("");
              expect(data.ContentInformation.RelevantSubfileName).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileName).to.be("");
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be("");
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be.a('boolean');
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanSharePointOnlineFile', function() {
        it('should call scanCloudStorageScanSharePointOnlineFile successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanSharePointOnlineFile call and complete the assertions
          /*
          var clientID = "clientID_example";
          var clientSecret = "clientSecret_example";
          var sharepointDomainName = "sharepointDomainName_example";
          var siteID = "siteID_example";
          var filePath = "filePath_example";
          var opts = {};
          opts.tenantID = "tenantID_example";
          opts.itemID = "itemID_example";

          instance.scanCloudStorageScanSharePointOnlineFile(clientID, clientSecret, sharepointDomainName, siteID, filePath, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContainsContentModerationRejection).to.be.a('boolean');
            expect(data.ContainsContentModerationRejection).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scanCloudStorageScanSharePointOnlineFileAdvanced', function() {
        it('should call scanCloudStorageScanSharePointOnlineFileAdvanced successfully', function(done) {
          // TODO: uncomment, update parameter values for scanCloudStorageScanSharePointOnlineFileAdvanced call and complete the assertions
          /*
          var clientID = "clientID_example";
          var clientSecret = "clientSecret_example";
          var sharepointDomainName = "sharepointDomainName_example";
          var siteID = "siteID_example";
          var opts = {};
          opts.tenantID = "tenantID_example";
          opts.filePath = "filePath_example";
          opts.itemID = "itemID_example";
          opts.allowExecutables = true;
          opts.allowInvalidFiles = true;
          opts.allowScripts = true;
          opts.allowPasswordProtectedFiles = true;
          opts.allowMacros = true;
          opts.allowXmlExternalEntities = true;
          opts.allowInsecureDeserialization = true;
          opts.allowHtml = true;
          opts.allowUnsafeArchives = true;
          opts.allowOleEmbeddedObject = true;
          opts.allowUnwantedAction = true;
          opts.restrictFileTypes = "restrictFileTypes_example";

          instance.scanCloudStorageScanSharePointOnlineFileAdvanced(clientID, clientSecret, sharepointDomainName, siteID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageAdvancedVirusScanResult);
            expect(data.Successful).to.be.a('boolean');
            expect(data.Successful).to.be(false);
            expect(data.CleanResult).to.be.a('boolean');
            expect(data.CleanResult).to.be(false);
            expect(data.ContainsExecutable).to.be.a('boolean');
            expect(data.ContainsExecutable).to.be(false);
            expect(data.ContainsInvalidFile).to.be.a('boolean');
            expect(data.ContainsInvalidFile).to.be(false);
            expect(data.ContainsScript).to.be.a('boolean');
            expect(data.ContainsScript).to.be(false);
            expect(data.ContainsPasswordProtectedFile).to.be.a('boolean');
            expect(data.ContainsPasswordProtectedFile).to.be(false);
            expect(data.ContainsRestrictedFileFormat).to.be.a('boolean');
            expect(data.ContainsRestrictedFileFormat).to.be(false);
            expect(data.ContainsMacros).to.be.a('boolean');
            expect(data.ContainsMacros).to.be(false);
            expect(data.ContainsXmlExternalEntities).to.be.a('boolean');
            expect(data.ContainsXmlExternalEntities).to.be(false);
            expect(data.ContainsInsecureDeserialization).to.be.a('boolean');
            expect(data.ContainsInsecureDeserialization).to.be(false);
            expect(data.ContainsHtml).to.be.a('boolean');
            expect(data.ContainsHtml).to.be(false);
            expect(data.ContainsUnsafeArchive).to.be.a('boolean');
            expect(data.ContainsUnsafeArchive).to.be(false);
            expect(data.ContainsOleEmbeddedObject).to.be.a('boolean');
            expect(data.ContainsOleEmbeddedObject).to.be(false);
            expect(data.VerifiedFileFormat).to.be.a('string');
            expect(data.VerifiedFileFormat).to.be("");
            {
              let dataCtr = data.FoundViruses;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(CloudmersiveVirusApiClient.CloudStorageVirusFound);
                expect(data.FileName).to.be.a('string');
                expect(data.FileName).to.be("");
                expect(data.VirusName).to.be.a('string');
                expect(data.VirusName).to.be("");

                      }
            }
            expect(data.ErrorDetailedDescription).to.be.a('string');
            expect(data.ErrorDetailedDescription).to.be("");
            expect(data.FileSize).to.be.a('number');
            expect(data.FileSize).to.be("0");
            expect(data.ContentInformation).to.be.a(CloudmersiveVirusApiClient.AdditionalAdvancedScanInformation);
                  expect(data.ContentInformation.ContainsJSON).to.be.a('boolean');
              expect(data.ContentInformation.ContainsJSON).to.be(false);
              expect(data.ContentInformation.ContainsXML).to.be.a('boolean');
              expect(data.ContentInformation.ContainsXML).to.be(false);
              expect(data.ContentInformation.ContainsImage).to.be.a('boolean');
              expect(data.ContentInformation.ContainsImage).to.be(false);
              expect(data.ContentInformation.Hash_SHA1).to.be.a('string');
              expect(data.ContentInformation.Hash_SHA1).to.be("");
              expect(data.ContentInformation.RelevantSubfileName).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileName).to.be("");
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be.a('string');
              expect(data.ContentInformation.RelevantSubfileHash_SHA1).to.be("");
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be.a('boolean');
              expect(data.ContentInformation.IsAuthenticodeSigned).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
