/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CloudStorageAdvancedVirusScanResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CloudStorageAdvancedVirusScanResult'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveVirusApiClient) {
      root.CloudmersiveVirusApiClient = {};
    }
    root.CloudmersiveVirusApiClient.ScanCloudStorageJobStatusResult = factory(root.CloudmersiveVirusApiClient.ApiClient, root.CloudmersiveVirusApiClient.CloudStorageAdvancedVirusScanResult);
  }
}(this, function(ApiClient, CloudStorageAdvancedVirusScanResult) {
  'use strict';

  /**
   * The ScanCloudStorageJobStatusResult model module.
   * @module model/ScanCloudStorageJobStatusResult
   * @version 1.3.1
   */

  /**
   * Constructs a new <code>ScanCloudStorageJobStatusResult</code>.
   * Status of the scan cloud storage job
   * @alias module:model/ScanCloudStorageJobStatusResult
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ScanCloudStorageJobStatusResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScanCloudStorageJobStatusResult} obj Optional instance to populate.
   * @return {module:model/ScanCloudStorageJobStatusResult} The populated <code>ScanCloudStorageJobStatusResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Successful'))
        obj.successful = ApiClient.convertToType(data['Successful'], 'Boolean');
      if (data.hasOwnProperty('AsyncJobStatus'))
        obj.asyncJobStatus = ApiClient.convertToType(data['AsyncJobStatus'], 'String');
      if (data.hasOwnProperty('AsyncJobID'))
        obj.asyncJobID = ApiClient.convertToType(data['AsyncJobID'], 'String');
      if (data.hasOwnProperty('Result'))
        obj.result = CloudStorageAdvancedVirusScanResult.constructFromObject(data['Result']);
      if (data.hasOwnProperty('JobDuration'))
        obj.jobDuration = ApiClient.convertToType(data['JobDuration'], 'String');
      if (data.hasOwnProperty('ErrorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['ErrorMessage'], 'String');
    }
    return obj;
  }

  /**
   * Tru eif the operation to check the status of the job was successful, false otherwise
   * @member {Boolean} successful
   */
  exports.prototype.successful = undefined;

  /**
   * Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
   * @member {String} asyncJobStatus
   */
  exports.prototype.asyncJobStatus = undefined;

  /**
   * Job ID of the async batch job
   * @member {String} asyncJobID
   */
  exports.prototype.asyncJobID = undefined;

  /**
   * Output scan result, if applicable
   * @member {module:model/CloudStorageAdvancedVirusScanResult} result
   */
  exports.prototype.result = undefined;

  /**
   * Duration of a completed job
   * @member {String} jobDuration
   */
  exports.prototype.jobDuration = undefined;

  /**
   * Error message (if any)
   * @member {String} errorMessage
   */
  exports.prototype.errorMessage = undefined;


  return exports;

}));
