/**
 * virusapi
 * Virus API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VirusScanResult', 'model/WebsiteScanRequest', 'model/WebsiteScanResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/VirusScanResult'), require('../model/WebsiteScanRequest'), require('../model/WebsiteScanResult'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveVirusApiClient) {
      root.CloudmersiveVirusApiClient = {};
    }
    root.CloudmersiveVirusApiClient.ScanApi = factory(root.CloudmersiveVirusApiClient.ApiClient, root.CloudmersiveVirusApiClient.VirusScanResult, root.CloudmersiveVirusApiClient.WebsiteScanRequest, root.CloudmersiveVirusApiClient.WebsiteScanResult);
  }
}(this, function(ApiClient, VirusScanResult, WebsiteScanRequest, WebsiteScanResult) {
  'use strict';

  /**
   * Scan service.
   * @module api/ScanApi
   * @version 1.1.3
   */

  /**
   * Constructs a new ScanApi. 
   * @alias module:api/ScanApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the scanFile operation.
     * @callback module:api/ScanApi~scanFileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VirusScanResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Scan a file for viruses
     * @param {File} inputFile Input file to perform the operation on.
     * @param {module:api/ScanApi~scanFileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VirusScanResult}
     */
    this.scanFile = function(inputFile, callback) {
      var postBody = null;

      // verify the required parameter 'inputFile' is set
      if (inputFile === undefined || inputFile === null) {
        throw new Error("Missing the required parameter 'inputFile' when calling scanFile");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'inputFile': inputFile
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = VirusScanResult;

      return this.apiClient.callApi(
        '/virus/scan/file', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the scanWebsite operation.
     * @callback module:api/ScanApi~scanWebsiteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WebsiteScanResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Scan a website for malicious content including viruses and threats (including Phishing)
     * @param {module:model/WebsiteScanRequest} input 
     * @param {module:api/ScanApi~scanWebsiteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/WebsiteScanResult}
     */
    this.scanWebsite = function(input, callback) {
      var postBody = input;

      // verify the required parameter 'input' is set
      if (input === undefined || input === null) {
        throw new Error("Missing the required parameter 'input' when calling scanWebsite");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = WebsiteScanResult;

      return this.apiClient.callApi(
        '/virus/scan/website', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
